### ISSUE TITLE
HSTS Headers Not Always Returned

### ISSUE THREAD

**Issue by storm2k** [roots/trellis#346] opened 2015-09-10 01:29 UTC
The SSL configuration of Trellis should pass a HSTS header when accessing any page on the site. Currently, accessing the site itself does not have the header returned, but accessing assets (like CSS files) on the site returns a HSTS header. [See discussion at Discourse](https://discourse.roots.io/t/ssl-config/4716).

**Comment by swalkinshaw** [comment] 2015-09-15 03:26
@storm2k just wanted to double check if you were using a recent version of Trellis on the server this occurs on?

**Comment by storm2k** [comment] 2015-09-17 20:45
The version is from July-ish, I cloned whatever was the latest version at the time, set it up following the example project structure.

**Comment by retlehs** [comment] 2015-11-02 05:43
also seeing this on a recent version of trellis (9 days old)

**Comment by retlehs** [comment] 2015-11-23 16:22
i'm not sure at what point this changed, but i'm pretty sure this is happening on all trellis installs now. it's resulting in the A rating instead of an A+ on SSL labs. (related: #416)

**Comment by swalkinshaw** [comment] 2015-11-29 01:27
Found out what's causing this. It was a regression caused by [FastCGI caching](https://github.com/roots/trellis/pull/234).

Nginx `add_header` under a `location` wipes out the headers from the `server` block. So once we added a header for the PHP files, the other headers are no longer present. Working on a fix for this.

**Closed** 2015-11-29 01:56 UTC
Labels: bug, help wanted
