### ISSUE TITLE
Homestead VS Trellis

### ISSUE THREAD

**Issue by nickkuijpers** [roots/trellis#420] opened 2015-11-20 23:25 UTC
Hello there,

# Little intro;

I've been programming in WordPress for like 2.5 years now, perfect but because the performance and the organizing of the file structure etc, (MVC, SOLID, etc..) i've changed to Laravel. Created some things in Laravel but then the question came. Can i manage my content like WordPress? So i've used the back-end of WP and integrated it in Laravel, perfect! Looking and searching online for some ways of doing that, i've come to Roots.io... Love at first sight!

I've had a Homestead development area ready and i've installed Bedrock and Sage. It was so fast but then i came to Trellis. Perfect deployment etc.. very nice! I've downloaded Trellis and migrated my WordPress environment to Trellis. 

Installed some plugins like Advanced Custom Fields Pro, Gravity Forms, SEO by Yoast.. for every plugin i've added, the website keeps getting slower.. So my feeling about a need for a lighter platform growth.. 

After opening WordPress in Trellis, the page toke 500ms to load while on Homestead it only toke 130ms. So weird, both the same WordPress installations, active plugins, MB RAM, changed processors to both 8 so they are the same, checked some more things to make sure they are 100% the same computer with a other Vagrant box on it.

# Question;

How come that Homestead, with like 5 plugins active, like on the Trellis environment, does not feel a thing about the amount of plugins active and stays at 130ms and Trellis keeps growing 100ms for each plugin i add? 

Trellis:

<img width="1440" alt="schermafbeelding 2015-11-21 om 00 17 36" src="https://cloud.githubusercontent.com/assets/5340923/11314375/500c3ecc-8fe5-11e5-93ba-57c8a13a2d2d.png">

Homestead: http://laravel.com/docs/5.1/homestead

<img width="1440" alt="schermafbeelding 2015-11-21 om 00 18 24" src="https://cloud.githubusercontent.com/assets/5340923/11314391/6baf9f16-8fe5-11e5-81f3-522180796834.png">

# Weird aye?

Does someone know which part of Homestead makes WordPress that fast? I haven't changed a thing in both the Vagrant boxes, just install and run.

**Comment by swalkinshaw** [comment] 2015-11-21 02:01
Thanks for reporting this + the numbers. Off the top of my head I don't know what the difference/problem could be. I assume Trellis does install and run more software than Homestead but I'm actually not sure from just looking at their list. Trellis is supposed to be as close to your staging/prod environments as possible while Homestead is for development only.

If anyone does any more investigation into this I'd be interested. @kalenjohnson might have some insight since he's used Laravel as well.

**Comment by evanfuture** [comment] 2015-11-21 05:09
Might be as simple as the domain name taking a bit to be resolved? That happens to me sometimes, even outside of Trellis. Can you test it on the bare ip address maybe?

**Comment by swalkinshaw** [comment] 2015-11-21 05:13
Wait I just noticed the queries and time.

Trellis: 14 queries in 496ms - full page in 554ms
Homestead: 11 queries in 143ms - full page in 169ms

So obviously this can't be directly compared.

**Comment by nickkuijpers** [comment] 2015-11-21 12:12
Thanks for your responses!

@evanfuture the domain names are both local with /etc/hosts so not difference ;(

@swalkinshaw that's the weird thing, both fresh install and same activation of plugins. No difference so why the queries are different, i don't know ;( I've really installed them on like 4 different machines but the queries keep stays the same. Same on Trellis and then same on Homestead.

**Comment by nickkuijpers** [comment] 2015-11-21 12:51
The different queries was the language and timezone i have selected on the one with more queries than the other. I've selected the language and timezone on Trellis now and the load time is now 700ms.

**Comment by swalkinshaw** [comment] 2015-11-21 15:19
@nickkuijpers not saying the queries will make a 300ms difference. But it makes the comparison less valid if they you aren't comparing the same things.

The latest query logs above still have different queries and more for Trellis.

**Comment by nickkuijpers** [comment] 2015-11-21 15:22
@swalkinshaw Hmm, i see indeed. But i don't think this is the problem. There is something else in Homestead that gives that amount of performance. I don't think we need to dive too deep in the same WordPress environments because when i install the test bedrock, i get the same results. This was just an indication with a WP Installation with 5 active plugins. 

What could it be? The variable that makes such a difference? I think this is an performance issue that gives such a optimization that it needs to be figured out don't you think? From 500ms to 120ms.

**Comment by mAAdhaTTah** [comment] 2015-11-21 15:57
The number of queries could be different if one has caching set up properly and the other doesn't.

**Comment by nickkuijpers** [comment] 2015-11-21 16:34
Okay so how to setup caching to get that performance on trellis?
Haventactivate caching or anything. Just install and run.

Op zaterdag 21 november 2015 heeft James DiGioia <notifications@github.com>
het volgende geschreven:

> The number of queries could be different if one has caching set up
> properly and the other doesn't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roots/trellis/issues/420#issuecomment-158658610>.
>


-- 
*Let op!*
Vanaf vrijdag 18 december'15 tot maandag 4 januari'16 voeren wij geen
programmering
werkzaamheden uit wegens vakantie. Indien aanwezigheid van storing wordt
u vriendelijk verzocht hier melding van te maken doormiddel van een sms
te versturen naar het telefoonnummer 06-26967629. Hierbij legt
u kort uit wat de storing is en waar deze zich plaatsvindt.

Onze servers worden 24/7 gemonitord. Heeft u even geduld voor dat u de
melding verstuurd
zodat u zeker weet dat dit een aanhoudende storing is. Is uw website
off-line?
Controleer of dit alleen voor u van toepassing is doormiddel van
de volgende website te gebruiken: http://ishetonline.nl.

**Comment by QWp6t** [comment] 2015-11-21 18:03
Shouldn't use caching in dev.

**Comment by QWp6t** [comment] 2015-11-21 18:06
According to that table you posted, it looks like you're using hhvm with homestead. Is that correct? And did you enable hhvm in trellis?

**Comment by QWp6t** [comment] 2015-11-21 18:12
Homestead is using more aggressive compression. Look at transfer sizes.

That's probably the main difference.

**Comment by nickkuijpers** [comment] 2015-11-21 18:40
What happens when you install 2 vagrant boxed, one trellis, one homestead? Then you install Bedrock and see the loadtime. I dont think Homestead adds caching because its used for dev also.

**Comment by kalenjohnson** [comment] 2015-11-21 18:45
Can you tell us what the differences between the queries are? It's pretty hard for and of us to guess at the differences

**Comment by nickkuijpers** [comment] 2015-11-21 19:06
Just some activated standard Widgets, further on nothing. The query's didn't take that long, as you can see in the second query log but there is something in Trellis that makes the time longer.. Do you know some tools i can check it with?

**Comment by kalenjohnson** [comment] 2015-11-21 20:22
How about https://wordpress.org/plugins/query-monitor/

**Comment by swalkinshaw** [comment] 2015-11-21 21:40
I'm closing this issue since it's gone a little off the rails. Thanks for reporting this @nickkuijpers but without some reproducible projects/instructions and direct comparisons there's not much we can do.

If someone wants to do more thorough research into this I'd be open to any solutions that make Trellis faster.

**Closed by swalkinshaw** 2015-11-21 21:40 UTC
