### ISSUE TITLE
mariadb role failing on re-provision

### ISSUE THREAD

**Issue by dgptamayo** [roots/trellis#1119] opened 2019-11-10 04:42 UTC
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Re-provisioning an existing vagrant server by running `vagrant provision` fails with errors in setting the root user password for mariadb:

```
TASK [mariadb : Set root user password] ****************************************
System info:
  Ansible 2.9.0; Vagrant 2.2.6; Darwin
  Trellis Head
---------------------------------------------------
unable to connect to database: (1045, "Access denied for user
'root'@'localhost' (using password: NO)")
failed: [default] (item=default) => {"ansible_loop_var": "item", "changed": false, "item": "default"}
---------------------------------------------------
unable to connect to database: (1045, "Access denied for user
'root'@'localhost' (using password: NO)")
failed: [default] (item=127.0.0.1) => {"ansible_loop_var": "item", "changed": false, "item": "127.0.0.1"}
---------------------------------------------------
unable to connect to database: (1045, "Access denied for user
'root'@'localhost' (using password: NO)")
failed: [default] (item=::1) => {"ansible_loop_var": "item", "changed": false, "item": "::1"}
---------------------------------------------------
unable to connect to database: (1045, "Access denied for user
'root'@'localhost' (using password: NO)")
failed: [default] (item=localhost) => {"ansible_loop_var": "item", "changed": false, "item": "localhost"}

```

## Steps to reproduce

1. Provision a new local development server - `vagrant up`
2. Re-provison - `vagrant provision`

**Expected behavior:**
Ansible provisioner playbooks complete succesfully

**Actual behavior:**
Playbook fails when executing `mariadb` role (specifically in setting root user password

**Reproduces how often:** 
Consistently

## Versions

Trellis v1.2.0
Ansible v2.9.0
OSX Sierra 10.12.6
Vagrant v2.2.6

**Comment by dgptamayo** [comment] 2019-11-10 04:54
### Update
This looks like an Ansible issue: https://github.com/ansible/ansible/issues/64560

**Comment by swalkinshaw** [comment] 2019-11-10 04:59
Good find, definitely seems like that's the issue. I'll keep this open anyway as a reminder to track that upstream issue.

**Comment by slackday** [comment] 2020-02-04 23:19
This issue also occured in Ansible v2.9.1. Trellis recommends Ansible 2.7.12 -> 2.8.4.

@dgptamayo I upgraded to Ansible v2.9.4 with `pip install ansible==2.9.4` on Mac and the issue is fixed in this version so it worked again for me.

**Comment by swalkinshaw** [comment] 2020-04-07 00:30
2.9.3 fixed this and Trellis supports it now.

https://github.com/ansible/ansible/blob/v2.9.6/changelogs/CHANGELOG-v2.9.rst#id8

**Closed by swalkinshaw** 2020-04-07 00:30 UTC
Labels: upstream bug

**Comment by davidvc** [comment] 2022-05-25 03:41
I got the same error and as far as I can tell I am using Ansible 2.10

```
davidvancouvering@davids-mbp siddhayoga.org % ./trellis/.trellis/virtualenv/bin/ansible --version
ansible 2.10.16
  config file = None
  configured module search path = ['/Users/davidvancouvering/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/davidvancouvering/projects/syda/siddhayoga.org/trellis/.trellis/virtualenv/lib/python3.10/site-packages/ansible
  executable location = ./trellis/.trellis/virtualenv/bin/ansible
  python version = 3.10.2 (main, Mar  5 2022, 16:40:30) [Clang 13.0.0 (clang-1300.0.29.30)]
```

**Comment by davidvc** [comment] 2022-05-25 03:49
> I got the same error and as far as I can tell I am using Ansible 2.10
> 
> ```
> davidvancouvering@davids-mbp siddhayoga.org % ./trellis/.trellis/virtualenv/bin/ansible --version
> ansible 2.10.16
>   config file = None
>   configured module search path = ['/Users/davidvancouvering/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /Users/davidvancouvering/projects/syda/siddhayoga.org/trellis/.trellis/virtualenv/lib/python3.10/site-packages/ansible
>   executable location = ./trellis/.trellis/virtualenv/bin/ansible
>   python version = 3.10.2 (main, Mar  5 2022, 16:40:30) [Clang 13.0.0 (clang-1300.0.29.30)]
> ```

Well, it went away when I manually removed mariadb and re-provisioned...
