### ISSUE TITLE
ANSIBLE_PATH breaks `vagrant global-status --prune`

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#296] opened 2015-08-11 04:12 UTC
If you have two or more roots-example-project type projects on your machine you might run into:

```
/Users/austinpray/DEV/project/project.com/Vagrantfile:6: warning: already initialized constant ANSIBLE_PATH
/Users/austinpray/DEV/roots.io/Vagrantfile:4: warning: previous definition of ANSIBLE_PATH was here
```

when running `vagrant global-status --prune`

**Comment by kalenjohnson** [comment] 2015-08-11 04:13
Confirmed, although I haven't used that vagrant command so I haven't noticed.

**Comment by austinpray** [comment] 2015-08-11 04:17
Also getting weird stuff like

```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/austinpray/DEV/roots.io/Vagrantfile
Line number: 11
Message: RuntimeError: group_vars/development file not found. Please set `ANSIBLE_PATH` in Vagrantfile
```

**Comment by kalenjohnson** [comment] 2015-08-11 05:55
I don't think we can just swap this constant for a local variable. So not really sure how exactly to fix this.

**Comment by louim** [comment] 2015-08-11 12:16
This is because the command is run in one "pass" over each vagrant environments, so the first definition of `ANSIBLE_PATH` is kept for the whole run. 

Changing it to a variable instead of a constant would work only if `vagrant global-status --prune` does not run in parallel, because it doesn't seems that vagrantfile are scoped.

**Comment by louim** [comment] 2015-08-15 18:16
Looking more into this, it seems the issue is upstream: https://github.com/mitchellh/vagrant/issues/5253. Current milestone is set to Vagrant 1.8

**Comment by swalkinshaw** [comment] 2015-10-15 03:28
Closing this since it's an upstream Vagrant issue.

**Closed by swalkinshaw** 2015-10-15 03:28 UTC
Labels: bug

**Comment by retlehs** [comment] 2017-06-28 01:05
this just happened to a colleague of mine running ansible 2.3 and vagrant 1.9.1.

the relevant fix:

> I had to login to the virtual machine in the VirtualBox app (couldn't SSH into the machine using the terminal) using the username/password vagrant.

> I also removed all references to the particular site in /etc/hosts/ as I noticed there were two references to the same site.

/via 
* https://discourse.roots.io/t/cannot-vagrant-up-virtualbox-machine-already-exists/6417/3
* http://magento.stackexchange.com/a/76501
