### ISSUE TITLE
  SSH to VM timeout due to DNS lookup timeout

### ISSUE THREAD

**Issue by zamber** [roots/trellis#249] opened 2015-06-25 09:52 UTC
OS: Arch, regular WiFi connection to a DHCP broadband router, nothing fancy.
Port forwarding works, everything in the network and NAT is pingable from the host and the client VM.

Provisioning fails, vagrant ssh fails silently. Debug here https://gist.github.com/zamber/e994dc827fd2bbbb8ffa (ignore paths, I substituted client dirs). This is extremely confusing behavior and can derail people easily.
After a day of investigation and double-checking I stumbled upon `UseDNS no` for fixing timeouts with SSH but it has to be set in `/etc/ssh/sshd_config` for the client VM.

`UseDNS` is just a [hindrance](https://unix.stackexchange.com/questions/56941/what-is-the-point-of-sshd-usedns-option) at this point and there's [talk](https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/424371) about changing the default configuration to `no` either ways.

I suggest setting it for the base box as it's impossible to provision without it in certain circumstances.

**Comment by swalkinshaw** [comment] 2015-06-26 12:42
@zamber would you be up for doing a PR to change this configuration?

**Comment by zamber** [comment] 2015-06-26 17:52
Would if I could. The problem is that no matter what authentication you would use (secure/insecure), you can't SSH to the VM to provision it. Tried changing timeouts on my side to no avail.

Fixing this requires changing the base box.

**Comment by fullyint** [comment] 2015-06-27 00:22
@zamber Do I understand correctly that you'd see the same timeouts and failed connection/provisioning if your `Vagrantfile` were to use `config.vm.box = 'ubuntu/trusty32'` instead of [`config.vm.box = 'roots/bedrock'`](https://github.com/roots/bedrock-ansible/blob/4f467c12f2071b7a9dc9449fccd3b57d2def4031/Vagrantfile#L26) because [`UseDNS` defaults to `yes`](http://manpages.ubuntu.com/manpages/trusty/en/man5/sshd_config.5.html)? If so, are you suggesting that the `roots/bedrock` box be set up with `UseDNS` set to `no`?

If so, that makes me wonder if the `sshd` role could be run always (not just as part of the `secure-root.yml` playbook), but only setting `PermitRootLogin` to `no` on an opt-in basis. The point would be for the `sshd` role to always set `UseDNS` to `no`. There might be some other adjustments required to accommodate vagrant, such as `Port` set to `2222` instead of `22`, I think.

**Comment by zamber** [comment] 2015-06-27 15:06
Had similar issues with VVV earlier but I didn't have time to investigate then. Soon after a friend recommended roots so I switched and hit the same issue again.

I tested with different `config.ssh.insert_key` on `ubuntu/trusty64` to be 100% sure, here's the log for both: https://gist.github.com/zamber/0a0acb6d3a01246b714a

~~I'm not sure if this is because my machine does not advertise it's hostname.~~ It didn't advertise it correctly. I could ping it without issues but for some reason the DNS resolver on Ubuntu wasn't able to discover it, possibly due to port forwarding but I also tried to SSH to `example.dev:22` and got the same symptoms. Had to fiddle around with dhcpcd and avahi to fix it. For future generations:
https://bbs.archlinux.org/viewtopic.php?id=158609
https://unix.stackexchange.com/questions/43762/how-do-i-get-to-use-local-hostnames-with-arch-linux
Restarting dbus froze my machine and I had to manually remove duplicated NFS mounts, though this can be due to the fast that I copied over the repo for testing.

Getting back to this issue, setting this on every playbook seems reasonable. Also `PermitRootLogin` set to `no` is something that should be done by default on exposed servers. If you're pre-provisioning the `roots/bedrock` vagrant box with then I would skip it and just set `UseDNS no`. Vagrant logs in as root to the box on first run to set locally generated keys for SSH.

Changing ports is not required as current configuration correctly forwards 22 to 2222 and aut0magically resolves any possible conflicts, so setting it manually could cause issues with that.

Moreover this probably is a non-issue for other distributions (and MacOS) that are ready OOTB to use. Nevertheless having SSH by default rely on clients advertising their hostname is quite odd.

Not sure if I should close this

**Comment by swalkinshaw** [comment] 2015-06-28 19:47
We already have the `sshd` role but it's currently only run from the `secure-root.yml` playbook. What should we do is always run the `sshd` role and just toggle the `sshd_permit_root_login` variable to remain at `yes` unless the user wants secure root. I believe that's the only default (and maybe `sshd_password_authentication`) that we won't want by default. Then we can add a variable to set `UseDNS` to `no`.

**Comment by zamber** [comment] 2015-07-01 09:54
How will this help when you can't ssh to the instance for provisioning when your host does not have its name advertised properly and UseDNS is defaulted to no? Or do you pre-provision the roots/bedrock box with ansible?

**Comment by austinpray** [comment] 2015-07-08 16:35
@zamber is this fixed now that we are using `ubuntu/trusty64`?

**Comment by zamber** [comment] 2015-07-08 17:23
Can't test as I fixed the underlying issue with my environment. 
On Jul 8, 2015 6:35 PM, Austin Pray <notifications@github.com> wrote:@zamber is this fixed now that we are using ubuntu/trusty64?

**Comment by fullyint** [comment] 2015-07-13 19:41
If we were still using the `roots/bedrock` box, we could have pre-provisioned it with `UseDNS no`. But it seems the [`ubuntu/trusty64` box we use now](https://github.com/roots/trellis/pull/260) will default `UseDNS yes`. So, the problem is upstream and needs to be addressed there. I think we can close this issue.

**Closed** 2015-07-13 19:43 UTC
