### ISSUE TITLE
Deploy.sh with HHVM Fatal Error

### ISSUE THREAD

**Issue by BrandonShutter** [roots/trellis#188] opened 2015-04-26 21:11 UTC
When you run deploy.yml with hhvm enabled, you get an error running `post_finalize_commands.`  This is due to it trying to restart `php5-fpm` without it existing.
```
TASK: [deploy | Run post_finalize_commands] *********************************** 
failed: [ipaddress] => (item=sudo service php5-fpm reload) => {"changed": true, "cmd": "sudo service php5-fpm reload", "delta": "0:00:00.016006", "end": "2015-04-26 17:10:04.735646", "item": "sudo service php5-fpm reload", "rc": 1, "start": "2015-04-26 17:10:04.719640", "warnings": []}
stderr: php5-fpm: unrecognized service

FATAL: all hosts have already failed -- aborting
```

**Comment by rstormsf** [comment] 2015-04-27 22:50
confirmed - face the same issue

**Comment by rstormsf** [comment] 2015-04-27 22:58
FIX:

https://github.com/roots/bedrock-ansible/blob/master/roles/deploy/defaults/main.yml#L85-L86

handle `if/else` if `hhvm` is true 
run 
`sudo service hhvm restart`

**Comment by rstormsf** [comment] 2015-04-27 23:01
For some reason, it just hangs there and is not ran. 
I had to manually ssh into and run
`
sudo service hhvm restart
`

**Comment by swalkinshaw** [comment] 2015-04-27 23:05
@rstormsf It's failing because of a sudoers issue. You can customize this variable: https://github.com/roots/bedrock-ansible/blob/5f97284dff3079563f5dcd811b9f27611a627135/roles/deploy/defaults/main.yml#L85-L86

```yaml
project_post_finalize_commands:
  - sudo service hhvm restart
```

And this is needed too:

```yaml
web_sudoers:
  - "/usr/sbin/service php5-fpm *"
  - "/usr/sbin/service hhvm *"
```

(or just remove php5-fpm if you aren't using it).

https://github.com/roots/bedrock-ansible/blob/5f97284dff3079563f5dcd811b9f27611a627135/group_vars/all#L17-L18

**Comment by CFXd** [comment] 2015-07-24 07:11
This is still an issue (bump)

**Comment by louim** [comment] 2015-07-24 12:59
@CFXd would you be interested doing a pull request? This should be easy to fix.

**Comment by CFXd** [comment] 2015-07-25 04:36
@louim not at this time—I only know enough to be dangerous :-/

**Comment by swalkinshaw** [comment] 2015-10-14 20:16
Fixed by https://github.com/roots/trellis/pull/378

**Closed by swalkinshaw** 2015-10-14 20:16 UTC
Labels: bug
