### ISSUE TITLE
AnsibleUndefinedVariable: {{ mailhog_install_dir }}/mhsendmail:

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#774] opened 2017-02-26 01:08 UTC
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

Ansible server.yml playbook isn't completely OK but fails with
```plain
AnsibleUndefinedVariable: {{ mailhog_install_dir }}/mhsendmail:
'mailhog_install_dir' is undefined
fatal: [192.168.50.5]: FAILED! => {"changed": false, "failed": true}
```

**What is the expected or desired behavior?**

Ansible playbook finishes with all OK.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

Edit:
Vagrant box [ubuntu/xenial64](https://atlas.hashicorp.com/ubuntu/boxes/xenial64) (on VirtualBox on Ubuntu 16.04.2).

**Please describe your local environment:**

Ansible version: 2.2.1.0

OS: Ubuntu 16.04.2

Vagrant version: Vagrant 1.9.1

**Where did the bug happen? Development or remote servers?**

Development

**Additional information**

`trellis/group_vars/development/mail.yml`:
```yml
# Documentation: https://roots.io/trellis/docs/mail/
php_sendmail_path: "{{ mailhog_install_dir }}/mhsendmail"
````
Variable mailhog_install_dir is used there and 

defined in `trellis/vendor/roles/mailhog/defaults/main.yml`:
````yml
---
mailhog_install_dir: /opt/mailhog
[...]
````

**Comment by swalkinshaw** [comment] 2017-02-26 01:32
Thanks for the detailed issue.

Unfortunately this is a very weird thing to run into but it shouldn't happen :( I'm not even sure what to say in terms of debugging.

Maybe delete your `vendor` dir and manually run again `ansible-galaxy install --force -r requirements.yml -p vendor/roles` again?

Or maybe re-install Ansible? Could try another version like 2.2.0

**Comment by strarsis** [comment] 2017-02-26 15:44
Things tried:

1. Removed vendor folder and repulled using ansible-galaxy.
Seems to reproduce the roles nicely, but still ends with same error.

2. Re-installed with a different version of ansible (2.2.0.0) and tried again.
Same error.



Vagrantfile for reproducing the issue:
````
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.hostname = "webtest"
  config.hostmanager.ip_resolver = proc do |machine|
    result = ""
    machine.communicate.execute("ifconfig enp0s8") do |type, data|
        result << data if type == :stdout
    end
    (ip = /inet addr:(\d+\.\d+\.\d+\.\d+)/.match(result)) && ip[1]
  end
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network", bridge: "ens33"
end
````

'~/.ssh/config':
````
Host webtest
  HostName webtest
  User ubuntu
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/build/test/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
````

'/etc/ansible/hosts':
```ini
[development]
webtest
````

And I had to update the public key in the Ubuntu box (it was somehow outdated):
'~/.ssh/authorized_keys':
````
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJfmgyUL2LSsprgYNjimLRn4gcVFS/CKpNniflg9eoCgAPNubqS3rl7CjmiWYmhO/1eIRZBOla09tjZiMT/UIUieCKZIdCdoHlICs4PDkMKR/IuMZ/dBc+r6Bghod8ColH5D4NApj+VR1qIJHdEVTexvXGgQvPUYEcEJoG7iFJYrZAsGX0CUavcTcIEXMzijT1YNCBJWmgM+lwgRkmLDt4usIcKTzdoGiybVNpLWyxfjss3NfjCNRMoIUYUdDeVLLIdNVUnijIVR91+6HkBFw3BjXSPGxVQl3zIrW0VhDQhu3dJnKO1S5F2XTn4hN1OuBhIyEhgHWxrTXeTPpNr7pj vagrant
`````

In the trellis folder of a web app, the ansible-playbook is ran:
````
$ ansible-playbook server.yml -e env=development -e 'ansible_ssh_user=admin'
````

**Comment by swalkinshaw** [comment] 2017-03-11 22:30
@strarsis did you ever figure this out? I'm still not sure what Trellis itself could do about it.

**Comment by strarsis** [comment] 2017-03-14 00:29
The issue is caused by a line in development default config that uses the variable: https://github.com/roots/trellis/blob/master/group_vars/development/mail.yml#L2
When the line is commented out, the error goes away - but not the underlying issue.

**Comment by fullyint** [comment] 2017-03-18 19:50
@strarsis I believe the problem stems from this entry in one of your hosts files:
```
[development]
web
```

Each of the Trellis [hosts files](https://github.com/roots/trellis/tree/2773baa313a496227eafbe294ca5b30d484c232a/hosts) lists a `[web]` group. This group name `web` should not be nested within (listed under) an `[<environment>]` group name like `[development]`.

You're running `server.yml` with `env=staging`. The implied [`hosts: web:&staging`](https://github.com/roots/trellis/blob/2773baa313a496227eafbe294ca5b30d484c232a/server.yml#L23) mean that Ansible will load group_vars corresponding to the `web` and `staging` groups. In normal Trellis, there are no group_vars for `web`. In your example, however, by nesting `web` within `development`, I believe you've caused `web` to inherit the group_vars of `development`.

You pointed out the problematic definition of `php_sendmail_path` from `group_vars/development/mail.yml`. That file's vars would not normally load for `-e env=staging`, and thus would not cause this issue, but I suppose that file's vars do load in your case because you've nested `web` under `development`.

Here is a [somewhat related discussion](https://discourse.roots.io/t/production-server-provision-configures-staging-envs-if-hosts-are-the-same-bug-or-intention/6090/2) that could shed light on the conflicts that can arise from inadvertently loading group_vars from multiple `env`s.

I'm not sure what goal led to nesting `web` under `development`, but you could propose to discuss unusual customizations at https://discourse.roots.io/. However, given that this appears to be a misconfiguration and not a bug for this GitHub bug tracker, I'm closing the issue.

**Closed by fullyint** 2017-03-18 19:50 UTC

**Comment by jeffbyrnes** [comment] 2021-07-21 15:12
I’ve run into this similar issue, and I _think_ it’s caused by using [`trellis-database-uploads-migration` and its aliased hosts configuration](https://github.com/valentinocossar/trellis-database-uploads-migration#-hosts-configuration).

Here’s my `group_vars/hosts/development` file contents:

```
[development]
development_host ansible_host=192.168.56.5 ansible_connection=ssh ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/default/virtualbox/private_key ansible_ssh_extra_args="-o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes"

[web]
development_host ansible_host=192.168.56.5 ansible_connection=ssh ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/default/virtualbox/private_key ansible_ssh_extra_args="-o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes"
```

And the similar error:

```
AnsibleUndefinedVariable: 'mailhog_install_dir' is undefined
fatal: [development_host]: FAILED! => {"changed": false}
```
