### ISSUE TITLE
NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#845] opened 2017-07-04 13:59 UTC
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums
---

**What is the current behavior?**

NET::ERR_CERT_DATE_INVALID for specific domain, certificate hadn't been renewed in time. 

Invoking the renew script manually results in it skipping the renewal because 
the certificate is assumed to be younger than 60 days:
````
Certificate file /etc/nginx/ssl/letsencrypt/example.com-b03bac4.cert already exists
  The certificate is younger than 60 days. Not creating a new certificate.
````

**What is the expected or desired behavior?**

That this never ever happens :trollface: .

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

The Trellis server has been provisioned for this site approximately 2 months ago, so the renewal somehow failed for it - or is it some kind of off-by-one error?

**Please describe your local environment:**

Ansible version: ansible 2.3.0.0

OS: Ubuntu 16.04.2 LTS

Vagrant version: (not applicable, production system)

**Where did the bug happen? Development or remote servers?**

Remote/production.

**Comment by swalkinshaw** [comment] 2017-07-12 00:43
> The Trellis server has been provisioned for this site approximately 2 months ago

Also meaning the version of Trellis you were using was about that old?

This seems strange to me since certificate expiry is 90 days. If renewal failed, the existing one should remain.

Considering that its ~2 months old, the message about being younger than 60 days seems correct?

**Comment by strarsis** [comment] 2017-07-27 11:51
@swalkinshaw:
Related discussion: https://discourse.roots.io/t/certbot-instead-acme-tiny/9051/6

So I had a similar certificate expire issue and I found out that in the cronfile for calling the renewal script, the days field value is still uninterpolated ansible variable!
````
#Ansible: letsencrypt certificate renewal
30 4 1,11,21 * * root cd /var/lib/letsencrypt && ./renew-certs.py && /usr/sbin/service nginx reload
    day: "{{ letsencrypt_cronjob_daysofmonth }}"
````

**Comment by fullyint** [comment] 2017-07-28 02:39
@strarsis That cron file is puzzling and I wasn't able to reproduce: my cron file is not created with the superfluous line: `day: "{{ letsencrypt_cronjob_daysofmonth }}"`

Given the presence of [`1,11,21`](https://github.com/roots/trellis/blob/dc6a58158536681612dc4d833ad5e8257da55d36/roles/letsencrypt/defaults/main.yml#L44) in the first line of the job,  it appears that the `letsencrypt_cronjob_daysofmonth` variable is being interpolated as part of the `day` parameter.

Of course, the strange part is the superfluous line: `day: "{{ letsencrypt_cronjob_daysofmonth }}"`. It looks a lot like somehow the newline that should be at the end of the `job` is not being interpreted such that the `job` value is including the next line `day`, with its four spaces of indentation. When I glance at the [module code](https://github.com/ansible/ansible/blob/v2.3.0.0-1/lib/ansible/modules/system/cron.py) for your version 2.3.0.0, I don't see any obvious questionable portion that could associated.

Any chance your text editor has added unusual or hidden characters or encodings in your file at `roles/letsencrypt/tasks/main.yml`? Perhaps you could turn on any "show hidden characters" options for this file in your text editor and investigate (especially in the area of the newline between `job` and `day`), or pull a fresh clone for testing.

Perhaps you could try removing `/etc/cron.d/letsencrypt-certificate-renewal` from the server and run the playbook again to see if the new cron file still has the problem. I only suspect it could be different this time if the cron file creation task was actually skipping in your recent retries.

**Comment by swalkinshaw** [comment] 2017-08-16 03:16
Closing without any way to reproduce. Feel free to re-open if it happens again.

**Closed by swalkinshaw** 2017-08-16 03:16 UTC
