### ISSUE TITLE
Fix Multisite

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#266] opened 2015-07-08 16:18 UTC
1. clone trellis
2. clone blank bedrock
3. configure development for multisite as per wiki instructions. For posterity here are the current multisite wiki instructions: https://gist.github.com/austinpray/b800ed3ec89987e6d784
4. vagrant up

It will error out. There are three problems I can see:

- [ ] wiki needs updating
- [x] [wp installed?](https://github.com/roots/trellis/blob/70ebd4527978ee88bfddd2d1b240f7c01ed20158/roles/wordpress-install/tasks/main.yml#L23-L30) task will always fail
- [x] No wildcard in nginx `server_name`

### wiki needs updating
I'm pretty sure you cannot add this stuff:

```
define('WP_ALLOW_MULTISITE', true);
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true); // Set to false if using subdirectories
define('DOMAIN_CURRENT_SITE', getenv('DOMAIN_CURRENT_SITE'));
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
```

Before running the playbook or it will cause DB errors.

### [wp installed?](https://github.com/roots/trellis/blob/70ebd4527978ee88bfddd2d1b240f7c01ed20158/roles/wordpress-install/tasks/main.yml#L23-L30) task will always fail
WordPress multisite will ALWAYS spit out garbage when trying to install. Which makes this: https://github.com/roots/trellis/blob/70ebd4527978ee88bfddd2d1b240f7c01ed20158/roles/wordpress-install/tasks/main.yml#L30 kinda flimsy. Perhaps we should just look at exit codes?

### No wildcard in nginx `server_name` for subdomains

We need to do this for subdomains:

```
server_name  example.dev  *.example.dev
```

Here is my hacked together code:

```
server_name {% for host in item.value.site_hosts %} {{ host }} {% if item.value.multisite.subdomains %} *.{{ host }} {% endif %} {% endfor %}
```

Please tell me jinja2 has some sort of prefix filter I don't know about.

**Comment by chriszarate** [comment] 2015-07-12 15:04
I'm using Trellis for a production subdomain multisite site. I use it as a dependency (via `requirements.yml`) for our own Ansible project. 

1. I also ran into the `wp installed` and multisite issues—however, it turned out that the `wordpress_install` role was too oriented towards new installs for our needs, so I supply my own `wordpress_install` role which overrides. Caveat: Our role is oriented towards creating AMIs/Vagrant boxes and not in having a WP instance up and ready. [Take a look][1] if you'd like. 

2. We have exactly your need for wildcard subdomains, but we simply list them in `site_hosts`:

```
site_hosts:
  - "example.dev"
  - "*.example.dev"
```

This doesn't cause any problems for us, but perhaps I'm missing something

[1]: https://github.com/mlaa/commons-playbooks

**Comment by QWp6t** [comment] 2015-07-13 02:18
Wildcard host is definitely the way to go. Otherwise a multisite network that allows public signups (such as wordpress.com) would not be possible.

I don't see a simple option for developers on Windows, however. Windows hosts file does not allow wildcards.

**Comment by alan-c** [comment] 2015-07-26 15:05
Some things I wanted to pass along:

1. @austinpray WP-CLI will add those lines at the end of the wp-config.php file when executing the `wp core multisite-install` command. Unfortunately that doesn't work with the file structure put in place by Bedrock, without a way to pass the path to application.php along with the command -- something I don't believe exists in WP-CLI. A play with a shell script shouldn't have any issue cleaning it up.

2. `- "*.example.dev"` in `site_hosts` leads to fatal DNS config issues when used to attempt a setup of development environment with Landrush - details [here](https://discourse.roots.io/t/multisite-provisioning-failure/4328).

3. `--url="{{ item.value.env.wp_home }}"` is required to eliminate the HTTP_HOST errors.

**Comment by mAAdhaTTah** [comment] 2015-07-26 15:35
FWIW, it feels like WP-CLI shouldn't do that, or at least have a flag to stop it from doing so. Worth opening an issue over there?

**Comment by alan-c** [comment] 2015-07-26 16:13
@mAAdhaTTah Admittedly I've been working on the process **without** manually placing `define('MULTISITE', true);` or the other lines in `config/application.php`. I'll look over at WP-CLI, but your comment jogged something in my brain -- I thought they had a scenario where they checked that constant or something similar when working on a multisite install.

**Comment by austinpray** [comment] 2015-07-29 17:19
@alan-c 

>- "*.example.dev" in site_hosts leads to fatal DNS config issues when used to attempt a setup of development environment with Landrush - details here.

Yep I ran into this and it completely killed my dev environment until I manually removed them from landrush.

**Comment by kalenjohnson** [comment] 2015-08-11 00:21
Ok so I just ran through this process again. Here's what worked for me:

* Set up a project in the same way Austin describes in OP.
* ONLY add `define('WP_ALLOW_MULTISITE', true);` to `bedrock/config/application.php`
* `vagrant up`
* Everything finishes, multisite installs.
* WP generally adds a bunch of defines to the end of `bedrock/web/wp-config.php`
  * Remove these constants
* Add the rest of the constants to `bedrock/config/application.php`

Bingo.

Still seems like a few steps too many. Originally, I believe changing the Trellis configs for multisite, adding the constants to Bedrock, and adding the landrush lines to the Vagrantfile was enough. It still will get stuck where Austin mentioned with the "wp installed?" task.

**Comment by rohmann** [comment] 2015-08-17 22:39
I was having similar issues working with Bedrock a while back (when it still came with Capistrano ).

The problem is that both the WordPress multisite installation process AND wp-cli rely heavily on the `is_multisite` function. Have a look, and you can get an idea why setting the constants in advance is problematic

https://github.com/WordPress/WordPress/blob/master/wp-includes/load.php#L721-L736

Unfortunately, because WordPress uses them for decision making during the install process, we need a way to control that. I'd propose updating the wiki, (and possibly even Bedrock) to something like:

```
define('WP_ALLOW_MULTISITE', true);
if (getenv('MULTISITE_INSTALLED')) {
  define('MULTISITE', true);
  define('SUBDOMAIN_INSTALL', getenv('SUBDOMAIN_INSTALL'));
  define('DOMAIN_CURRENT_SITE', getenv('DOMAIN_CURRENT_SITE'));
  define('PATH_CURRENT_SITE', '/');
  define('SITE_ID_CURRENT_SITE', 1);
  define('BLOG_ID_CURRENT_SITE', 1);
}
```

The trick would be fact checking for the `MULTISITE_INSTALLED` env variable. The  `wp core is-installed` command has a `--network` flag, but it's not much use because it relies on the `is_multisite` function which will not be returning true at this point.

We could check for the presence of any of the multisite tables though. For example, running...

`wp db tables | grep -i sitemeta`

...should give output if the `{$prefix}_sitemeta` table exists, proving Multisite has installed it's tables.

I'm still getting familiarized with Ansible, so I don't have a working example. If I have time in the next few weeks I'll explore further, but definitely wanted to share my thoughts so far in case it helps anyone in their experimenting.

**Comment by rohmann** [comment] 2015-08-17 23:11
haha sorry @alan-c I'm just now seeing your PR. Great stuff.

**Comment by fabianhenzler** [comment] 2015-08-18 15:02
ok... is there any step-by-step guide or any example project of trellis with bedrock and a MultiSite yet? Could anyone assist me? :)

**Comment by kalenjohnson** [comment] 2015-08-18 17:58
@fabianhenzler the fixes are still rather in development, but they seem to be working ok at the pull request here: https://github.com/roots/trellis/pull/283

I think a little more testing will be done, but it should be committed to Trellis soon with an update to the wiki.

**Closed** 2015-08-29 20:11 UTC
Labels: bug, help wanted
